import { LOGO_PARTS, LOGO_VIEWBOX } from "@/lib/logo";

/* The Voltwise wordmark from its own ten vector parts (lib/logo.ts, generated by scripts/logo.py). It takes
   `currentColor`, so it follows the header tone. `parts` tags every shape with data-part for the preloader. */
export function Logo({ title = "Voltwise", parts = false, className = "" }: { title?: string; parts?: boolean; className?: string }) {
  return <svg className={`logo ${className}`} viewBox={LOGO_VIEWBOX} role={title ? "img" : undefined} aria-label={title || undefined} aria-hidden={title ? undefined : true} focusable="false" fill="currentColor">
    {LOGO_PARTS.map((p) => <path key={p.id} d={p.d} data-part={parts ? p.id : undefined} />)}
  </svg>;
}
