// Generated by scripts/map.mjs. Do not edit by hand.
// Outline: public/media/uk-map.svg (Natural Earth 1:10m, Mercator fitted to both islands). Points: read off the
// live /projects map image and projected into the same 582×760 frame.
export const MAP_W = 582;
export const MAP_H = 760;
export const PROJECT_POINTS = [
  {
    "name": "Erskine",
    "mw": 30,
    "lat": 55.89,
    "lon": -4.27,
    "x": 294.4,
    "y": 306.6
  },
  {
    "name": "Drumcross",
    "mw": 30,
    "lat": 55.89,
    "lon": -3.483,
    "x": 328.7,
    "y": 306.6
  },
  {
    "name": "Barnsley",
    "mw": 40,
    "lat": 53.605,
    "lon": -1.416,
    "x": 418.7,
    "y": 479.1
  },
  {
    "name": "Newtonwood",
    "mw": 50,
    "lat": 53.236,
    "lon": -1.315,
    "x": 423.1,
    "y": 506.1
  },
  {
    "name": "Wolverhampton",
    "mw": 50,
    "lat": 52.605,
    "lon": -2.18,
    "x": 385.4,
    "y": 551.7
  },
  {
    "name": "Burwell I",
    "mw": 50,
    "lat": 52.38,
    "lon": 0.168,
    "x": 487.7,
    "y": 567.7
  },
  {
    "name": "Burwell II",
    "mw": 30,
    "lat": 52.38,
    "lon": 0.528,
    "x": 503.4,
    "y": 567.7
  },
  {
    "name": "Brook Farm",
    "mw": 50,
    "lat": 52.125,
    "lon": 1.078,
    "x": 527.4,
    "y": 585.9
  },
  {
    "name": "Berkeley",
    "mw": 50,
    "lat": 51.722,
    "lon": -2.349,
    "x": 378.1,
    "y": 614.4
  },
  {
    "name": "Brentwood",
    "mw": 50,
    "lat": 51.692,
    "lon": 0.337,
    "x": 495.1,
    "y": 616.4
  },
  {
    "name": "North Tawton",
    "mw": 30,
    "lat": 50.739,
    "lon": -3.832,
    "x": 313.5,
    "y": 682.8
  }
];
