// Generated by scripts/map.mjs. Do not edit by hand.
// Outline: public/media/uk-map.svg (Natural Earth 1:10m, Mercator fitted to Great Britain). Points: read off the
// live /projects map image and projected into the same 560×760 frame.
export const MAP_W = 560;
export const MAP_H = 760;
export const PROJECT_POINTS = [
  {
    "name": "Erskine",
    "mw": 30,
    "lat": 55.89,
    "lon": -4.27,
    "x": 185.1,
    "y": 268.5
  },
  {
    "name": "Drumcross",
    "mw": 30,
    "lat": 55.89,
    "lon": -3.483,
    "x": 222,
    "y": 268.5
  },
  {
    "name": "Barnsley",
    "mw": 40,
    "lat": 53.605,
    "lon": -1.416,
    "x": 319.2,
    "y": 454.6
  },
  {
    "name": "Newtonwood",
    "mw": 50,
    "lat": 53.236,
    "lon": -1.315,
    "x": 323.9,
    "y": 483.7
  },
  {
    "name": "Wolverhampton",
    "mw": 50,
    "lat": 52.605,
    "lon": -2.18,
    "x": 283.3,
    "y": 532.9
  },
  {
    "name": "Burwell I",
    "mw": 50,
    "lat": 52.38,
    "lon": 0.168,
    "x": 393.6,
    "y": 550.2
  },
  {
    "name": "Burwell II",
    "mw": 30,
    "lat": 52.38,
    "lon": 0.528,
    "x": 410.5,
    "y": 550.2
  },
  {
    "name": "Brook Farm",
    "mw": 50,
    "lat": 52.125,
    "lon": 1.078,
    "x": 436.4,
    "y": 569.8
  },
  {
    "name": "Berkeley",
    "mw": 50,
    "lat": 51.722,
    "lon": -2.349,
    "x": 275.4,
    "y": 600.5
  },
  {
    "name": "Brentwood",
    "mw": 50,
    "lat": 51.692,
    "lon": 0.337,
    "x": 401.5,
    "y": 602.7
  },
  {
    "name": "North Tawton",
    "mw": 30,
    "lat": 50.739,
    "lon": -3.832,
    "x": 205.7,
    "y": 674.3
  }
];
