"""Splits voltwisepower.com's own wordmark SVG ("Voltwise White Logo.svg", 151 x 30.95) into its ten vector parts
and writes lib/logo.ts, so the preloader can assemble the name letter by letter.

The mark is a wordmark only (no separate symbol). Its two signature cuts are what the preloader plays up:
  t-flag   the crossbar's right half is a separate wedge
  i        the dot is not a dot: the stem rises with a slanted cut (a spark)
  s        drawn as two halves split by a diagonal bolt
Run: python3 scripts/logo.py"""
import re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
svg = (root / "_scrape/raw/logo-white.svg").read_text()
paths = re.findall(r'<path d="([^"]+)"', svg)
names = ["v", "o", "l", "t", "t-flag", "w", "i", "s-low", "s-high", "e"]
assert len(paths) == len(names), len(paths)

out = ["// Generated by scripts/logo.py from voltwisepower.com's \"Voltwise White Logo.svg\". Do not edit by hand.",
       "export const LOGO_VIEWBOX = \"0 0 151 31\";", "", "export const LOGO_PARTS = ["]
for n, d in zip(names, paths):
    out.append(f"  {{ id: \"{n}\", d: \"{d}\" }},")
out.append("] as const;")
(root / "lib/logo.ts").write_text("\n".join(out) + "\n")
print("wrote lib/logo.ts with", len(paths), "parts")
